//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetambwegaWardDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetambwegaWard
    {
        public string wardId { get; set; }
        public Nullable<double> rainfall { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<int> al6 { get; set; }
        public Nullable<int> al12 { get; set; }
        public Nullable<int> al18 { get; set; }
        public Nullable<int> al24 { get; set; }
        public System.DateTime months { get; set; }
    }
}
