using Microsoft.ML.Data;

namespace API.DataModels
{

    //MalariaPrediction inherits from PrevalenceData.
    //This makes it easier to see the original data in the fields property along with the output generated by the model.
    public class MalariaPrevalencePrediction : PrevalenceData
    {
        [ColumnName("PredictedLabel")]
        public float Prediction { get; set; }

    }
}